// dsh-usage-panel · stylesheet (injected with data-plugin-css lifecycle).
// v0.1.0 CSS ported verbatim (class names stable) + new card styles. Themed
// with --dsw-* aliases and the dark-theme heatmap ramp.
export const STYLE_ID = 'dsh-usage-panel/styles'

export const CSS = [
  '.dsw-ust-root{position:relative;display:flex;flex-direction:column;gap:14px;padding:18px 20px 28px;min-width:0}',
  '.dsw-ust-tooltip{position:fixed;left:0;top:0;transform:translate(-50%,-110%);background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);padding:5px 10px;border-radius:6px;font-size:11px;white-space:nowrap;pointer-events:none;box-shadow:0 2px 8px rgba(0,0,0,.06);opacity:0;transition:opacity .1s;z-index:9999}',
  '.dsw-ust-tooltip.show{opacity:1}',
  '.dsw-ust-tooltip-title{font-size:11px;font-weight:600;color:var(--dsw-alias-label-primary);margin-bottom:4px;white-space:nowrap}',
  '.dsw-ust-tooltip-row{display:flex;align-items:center;gap:6px;font-size:11px;color:var(--dsw-alias-label-secondary);white-space:nowrap;line-height:1.6}',
  '.dsw-ust-tooltip-row i{width:8px;height:8px;border-radius:50%;flex-shrink:0;display:inline-block}',
  '.dsw-ust-tooltip-row .dsw-ust-tooltip-label{flex:1;color:var(--dsw-alias-label-primary)}',
  '.dsw-ust-tooltip-row .dsw-ust-tooltip-value{color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums}',
  '.dsw-ust-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}',
  '.dsw-ust-head h2{margin:0;font-size:16px;font-weight:650;color:var(--dsw-alias-label-primary)}',
  '.dsw-ust-head-title{display:flex;align-items:flex-start;gap:8px;min-width:0}',
  '.dsw-ust-page-icon{flex-shrink:0;margin-top:2px;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-sub{margin-top:3px;font-size:11px;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-head-actions{display:flex;align-items:center;gap:8px;flex-shrink:0}',
  '.dsw-ust-refresh{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);border-radius:8px;padding:6px 11px;font-size:12px;cursor:pointer}',
  '.dsw-ust-refresh:hover{border-color:var(--dsw-alias-border-l2)}',
  '.dsw-ust-refresh:disabled{opacity:.55;cursor:default}',
  '.dsw-ust-export{position:relative}',
  '.dsw-ust-export-menu{position:absolute;right:0;top:calc(100% + 4px);min-width:150px;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:4px;box-shadow:0 4px 16px rgba(0,0,0,.12);z-index:9000}',
  '.dsw-ust-export-menu button{display:block;width:100%;text-align:left;border:none;background:transparent;color:var(--dsw-alias-label-primary);font-size:12px;padding:7px 10px;border-radius:6px;cursor:pointer}',
  '.dsw-ust-export-menu button:hover{background:var(--dsw-alias-bg-layer-2)}',
  '.dsw-ust-card{background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:14px 16px;min-width:0}',
  '.dsw-ust-card-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px;flex-wrap:wrap}',
  '.dsw-ust-card h3{margin:0 0 12px;font-size:13px;font-weight:600;color:var(--dsw-alias-label-primary)}',
  '.dsw-ust-card-head h3{margin:0}',
  '.dsw-ust-card-title{display:flex;align-items:baseline;gap:8px;min-width:0}',
  '.dsw-ust-card-sub{font-size:11px;font-weight:400;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}',
  '.dsw-ust-kpi{background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:13px 15px;min-width:0}',
  '.dsw-ust-kpi .l{font-size:11px;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-kpi .v{margin-top:7px;font-size:19px;font-weight:700;color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums;line-height:1.2;word-break:break-all}',
  '.dsw-ust-kpi .v-sm{font-size:15px}',
  '.dsw-ust-kpi .d{margin-top:4px;font-size:11px;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-range{display:inline-flex;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;overflow:hidden;flex-shrink:0}',
  '.dsw-ust-range button{border:none;background:transparent;color:var(--dsw-alias-label-secondary);font-size:11px;padding:5px 11px;cursor:pointer}',
  '.dsw-ust-range button:hover{color:var(--dsw-alias-label-primary)}',
  '.dsw-ust-range button.on{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font-weight:600}',
  '.dsw-ust-chart{width:100%;height:auto;display:block}',
  '.dsw-ust-axis{fill:var(--dsw-alias-label-secondary);font-size:10px;font-family:inherit}',
  '.dsw-ust-legend{display:flex;flex-wrap:wrap;gap:6px 14px;margin-top:10px}',
  '.dsw-ust-legend-item{display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-legend-item i{width:9px;height:9px;border-radius:3px;display:inline-block}',
  '.dsw-ust-models{display:flex;gap:18px;align-items:center;flex-wrap:wrap}',
  '.dsw-ust-donut{flex-shrink:0}',
  '.dsw-ust-donut-seg{cursor:pointer;transition:stroke-width .15s}',
  '.dsw-ust-donut-seg:hover{stroke-width:28px}',
  '.dsw-ust-donut-total{fill:var(--dsw-alias-label-primary);font-size:17px;font-weight:700;font-family:inherit}',
  '.dsw-ust-donut-cap{fill:var(--dsw-alias-label-secondary);font-size:10px;font-family:inherit}',
  '.dsw-ust-mlist{flex:1 1 190px;min-width:170px}',
  '.dsw-ust-mhead{display:flex;align-items:center;gap:9px;padding:0 2px 6px;font-size:10px;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-mhead .h-model{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dsw-ust-mhead .h-share{width:52px;text-align:right}',
  '.dsw-ust-mhead .h-rate{width:56px;text-align:right}',
  '.dsw-ust-mrate{width:56px;text-align:right;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums;white-space:nowrap;flex-shrink:0}',
  '.dsw-ust-mrow{display:flex;align-items:center;gap:9px;padding:6px 2px;font-size:12px;min-width:0}',
  '.dsw-ust-mrow+.dsw-ust-mrow{border-top:1px solid var(--dsw-alias-border-l1)}',
  '.dsw-ust-dot{width:9px;height:9px;border-radius:50%;flex-shrink:0}',
  '.dsw-ust-mname{flex:1;color:var(--dsw-alias-label-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}',
  '.dsw-ust-mtokens{color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums}',
  '.dsw-ust-mpct{width:52px;text-align:right;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}',
  '.dsw-ust-empty{background:var(--dsw-alias-bg-layer-1);border:1px dashed var(--dsw-alias-border-l2);border-radius:12px;padding:34px 20px;text-align:center;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.8}',
  '.dsw-ust-empty-title{font-size:14px;font-weight:600;color:var(--dsw-alias-label-primary);margin-bottom:4px}',
  '.dsw-ust-heat-wrap{position:relative;display:flex;gap:0;align-items:flex-start;overflow-x:auto;padding-bottom:2px;scrollbar-width:none;-ms-overflow-style:none}',
  '.dsw-ust-heat-wrap::-webkit-scrollbar{display:none}',
  '.dsw-ust-heat-weekdays{position:absolute;left:0;top:17px;bottom:2px;display:grid;grid-template-rows:repeat(7,1fr);gap:3px;width:10px;font-size:10px;color:var(--dsw-alias-label-secondary);margin:0}',
  '.dsw-ust-heat-weekdays span{display:flex;align-items:center;align-self:center;height:12px;line-height:12px}',
  '.dsw-ust-heat-main{min-width:0;flex:1 1 auto;margin-left:18px}',
  '.dsw-ust-heat-months{display:grid;gap:3px;width:100%;height:14px;margin-bottom:3px;font-size:10px;color:var(--dsw-alias-label-secondary)}',
  '.dsw-ust-heat-month{white-space:nowrap;min-width:0}',
  '.dsw-ust-heat{display:grid;grid-auto-flow:column;grid-template-rows:repeat(7,auto);width:100%;min-width:max-content;gap:3px}',
  '.dsw-ust-heat-cell{aspect-ratio:1/1;border-radius:2px;cursor:default}',
  '.dsw-ust-heat-cell:hover{box-shadow:0 0 0 1px var(--dsw-alias-border-l2)}',
  '.dsw-ust-heat-blank{background:transparent;cursor:default}',
  '.dsw-ust-h0{background:#eef2f7}',
  '.dsw-ust-h1{background:#dbeafe}',
  '.dsw-ust-h2{background:#93c5fd}',
  '.dsw-ust-h3{background:#3b82f6}',
  '.dsw-ust-h4{background:#1d4ed8}',
  'body[data-ds-dark-theme] .dsw-ust-h0{background:#1f2937}',
  'body[data-ds-dark-theme] .dsw-ust-h1{background:#1e3a8a}',
  'body[data-ds-dark-theme] .dsw-ust-h2{background:#2563eb}',
  'body[data-ds-dark-theme] .dsw-ust-h3{background:#3b82f6}',
  'body[data-ds-dark-theme] .dsw-ust-h4{background:#60a5fa}',
  '.dsw-ust-heat-legend{display:flex;align-items:center;gap:5px;font-size:11px;color:var(--dsw-alias-label-secondary);flex-shrink:0}',
  '.dsw-ust-heat-swatch{width:10px;height:10px;border-radius:2px;display:inline-block}',
  '.dsw-ust-bar-seg{transform-origin:bottom;transform-box:fill-box;animation:dsw-ust-bar-grow .9s cubic-bezier(.16,1,.3,1) both}',
  '.dsw-ust-donut-seg{transform-box:fill-box;transform-origin:center;animation:dsw-ust-donut-spin .9s cubic-bezier(.16,1,.3,1) both}',
  '@keyframes dsw-ust-bar-grow{from{transform:scaleY(0)}to{transform:scaleY(1)}}',
  '@keyframes dsw-ust-donut-spin{from{transform:rotate(-90deg)}to{transform:rotate(270deg)}}',
  // ---- v0.2 additions ----
  '.dsw-ust-coverage{display:flex;flex-wrap:wrap;gap:6px 18px;font-size:11px;color:var(--dsw-alias-label-secondary);line-height:1.8}',
  '.dsw-ust-coverage b{color:var(--dsw-alias-label-primary);font-weight:600}',
  '.dsw-ust-coverage .warn{color:#d97706;font-weight:600}',
  'body[data-ds-dark-theme] .dsw-ust-coverage .warn{color:#fbbf24}',
  '.dsw-ust-srow{display:flex;align-items:center;gap:10px;padding:7px 2px;font-size:12px;min-width:0}',
  '.dsw-ust-srow+.dsw-ust-srow{border-top:1px solid var(--dsw-alias-border-l1)}',
  '.dsw-ust-srank{width:20px;flex-shrink:0;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums;font-size:11px}',
  '.dsw-ust-sname{flex:1;color:var(--dsw-alias-label-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}',
  '.dsw-ust-smeta{font-size:11px;color:var(--dsw-alias-label-secondary);white-space:nowrap;flex-shrink:0}',
  '.dsw-ust-stokens{color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums;white-space:nowrap;flex-shrink:0}',
  '.dsw-ust-prow{display:flex;align-items:center;gap:10px;padding:6px 2px;font-size:12px;min-width:0}',
  '.dsw-ust-prow+.dsw-ust-prow{border-top:1px solid var(--dsw-alias-border-l1)}',
  '.dsw-ust-pbar{flex:1;height:6px;border-radius:3px;background:var(--dsw-alias-bg-layer-2);overflow:hidden;min-width:60px}',
  '.dsw-ust-pbar i{display:block;height:100%;border-radius:3px}',
  '.dsw-ust-pname{width:140px;color:var(--dsw-alias-label-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex-shrink:0}',
  '.dsw-ust-ptokens{color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums;white-space:nowrap;flex-shrink:0}',
].join('\n')
